# Generated by Django 6.0.4 on 2026-05-01 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0004_lot_blockchain_status_lot_retry_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='statut',
            field=models.CharField(choices=[('cree', 'Créé'), ('en_transit', 'En transit'), ('receptionne', 'Réceptionné'), ('certifie', 'Certifié'), ('exporte', 'Exporté')], default='cree', max_length=20),
        ),
    ]
